<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <!-- ✅ Keep views editable at runtime -->
	  <MvcRazorCompileOnPublish>false</MvcRazorCompileOnPublish>
	  <MvcRazorCompileOnBuild>false</MvcRazorCompileOnBuild>
	  <PreserveCompilationContext>true</PreserveCompilationContext>

	  <!-- ✅ Required so MSBuild doesn’t skip views -->
	  <EnableDefaultContentItems>false</EnableDefaultContentItems>
	  <CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.3.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.21" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\backoffice\download\" />
  </ItemGroup>
	<ItemGroup>

		<Content Include="Views\**\*.cshtml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
		<Content Include="Areas\**\Views\**\*.cshtml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
		<Content Include="Pages\**\*.cshtml" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Always" />
		<Content Include="wwwroot\**\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
		<!--<Content Include="appsettings*.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />-->
	</ItemGroup>
	<Target Name="CopyViewsAfterPublish" AfterTargets="Publish">
		<ItemGroup>
			<_CustomViews Include="$(ProjectDir)Views\**\*.cshtml" />
		</ItemGroup>
		<Copy SourceFiles="@(_CustomViews)" DestinationFolder="$(PublishDir)Views\%(RecursiveDir)" />
	</Target>
</Project>
